micronaut:
  application:
    name: micronaut3ThymeleafBasicDemo
  router:
    static-resources:
      css:
        enabled: true
        mapping: /css/**
        paths: classpath:static/css
netty:
  default:
    allocator:
      max-order: 3
